### ISSUE TITLE
can't turn it on

### ISSUE THREAD

**Issue by ultra-beep** [hasan-py/MERN_Stack_Project_Ecommerce_Hayroo#14]
![image](https://user-images.githubusercontent.com/79453405/187088425-cceef027-66e5-45e3-a9f5-dbe89f1e42b8.png)

**Comment by hasan-py** [comment]
Are you resolved that?

**Comment by ultra-beep** [comment]
No can't find a way to fix it

**Comment by ultra-beep** [comment]
Ye i fixed it alr

**Comment by ultra-beep** [comment]
no its still there

**Comment by hasan-py** [comment]
You can check this out: https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported

**Comment by ultra-beep** [comment]
that worked and could you tell me pls what BRAINTREE_MERCHANT_ID=
BRAINTREE_PUBLIC_KEY=
BRAINTREE_PRIVATE_KEY=
Means?
and if i open the shop every user that makes a acc can get to the dashboard how do i change this ?

**Comment by ultra-beep** [comment]
and how do i make it so not every1 that has a acc can open the admin panel ?

**Comment by hasan-py** [comment]
Can't understand! Can you explain in details please?

**Comment by ultra-beep** [comment]
you know at the top right corner you are able to login / make a acc and
when you make a acc and log in you will see the popup to go to the admin
panel.
And i want to know if you know how i can fix it so only certain ppl can
acces the admin panel.

Op vr 14 okt. 2022 om 06:15 schreef Hasan ***@***.***>:

**Comment by hasan-py** [comment]
Got it. You want that, certain people can just access the admin panel? This is already implemented. You can create customer and admin both. And for serve this purpose, you need to change some code in the backend codebase. I Commented it into the server.js file in the backend codebase. I hope you got it. If not then let me know. You can DM me on Twitter for a fast response https://twitter.com/hasan_py

Thank you for your time. I'm closing this issue.

**Comment by ultra-beep** [comment]
or i'm blind but there is no server.js file
