### ISSUE TITLE
Brother you are a dope developer how did u learn so much???

### ISSUE THREAD

**Issue by aryabyte21** [hasan-py/MERN_Stack_Project_Ecommerce_Hayroo#15]
Please let me know in the comments. How do u code so much do u read documentation or do you watch video tutorials and do u listen to music while programming.

**Comment by hasan-py** [comment]
Yes, brother! documentation and problem-solving. Problem-solving for logic build-up and docs will help with fundamentals.

**Comment by hasan-py** [comment]
Yes, brother! documentation and problem-solving. Problem-solving for logic build-up and docs will help with fundamentals.
