### ISSUE TITLE
Business Logic leak 

### ISSUE THREAD

**Issue by Mounir24** [hasan-py/MERN_Stack_Project_Ecommerce_Hayroo#21]
Hey Hassan ! i've saw your project online , i am a fan of MERN stack web , so i've review your source code , there's a lot of issues , and leak of business logic , and bugs

![Screen Shot 2023-04-25 at 04 59 21](https://user-images.githubusercontent.com/58659995/234163887-c37f919f-05c3-4f11-b8ec-874c91d31110.png)

one of them, in this API endpoint , /api/user/edit-user , to provide the user an ability to update its profile data , in this case , you miss the proper validation of user's ID , i can bypass this and update someone else profile by getting its ID .

there's a lot of issues , i just liked your project  , and decide to go along with it .

**Comment by hasan-py** [comment]
Hi @Mounir24 👋 I'm glad you liked my project and took the time to review the code. I agree that there are several issues and bugs that need to be fixed, including the one you mentioned with the API endpoint for updating user profiles. It was a fun project when I started and now there are a lot of people reviewing it every day, So now it's really important to fix all the issues. I would be happy if you contribute to this project and help resolve these issues. I believe that your expertise can improve the code quality, implement proper validation, and enhance the overall functionality of the project.
