### ISSUE TITLE
about the database and the website loadig issue

### ISSUE THREAD

**Issue by kunal-suraa** [hasan-py/MERN_Stack_Project_Ecommerce_Hayroo#23]
About the database connectivity in the project the database error keep comming in the terminal please tell me that how to solve this error and make the website as working as yours
![WhatsApp Image 2023-04-30 at 11 59 44 AM](https://user-images.githubusercontent.com/132188195/235339456-98305e34-8904-439a-8839-5ab079a9adc7.jpeg)

**Comment by kunal-suraa** [comment]
can you please provide me your number so i can contact you  for the project

**Comment by kunal-suraa** [comment]
i need e commerce website till tomorrow please help me to get that source code

**Comment by hasan-py** [comment]
Hey there! Sorry for the late reply. I think you don't install MongoDB on your local machine, Please share the database error here or you can DM me on Twitter or Linkedin.

- Linkedin : https://www.linkedin.com/in/hasan-py/
- Twitter : @hasan_py

Thanks!
