### ISSUE TITLE
payment methode

### ISSUE THREAD

**Issue by zrdouane** [hasan-py/MERN_Stack_Project_Ecommerce_Hayroo#25]
how i can delete the payment and submit without BRAINTREE methode just fill the email , number

**Comment by hasan-py** [comment]
You emailed me earlier today, and I am replying to you here. Thank you for reaching out, dear.

**Comment by zrdouane** [comment]
fixed bro thank you

**Comment by nyazkhan** [comment]
I have same doubt can you please help me with the same
