### ISSUE TITLE
Loading Icon Spin Clockwise (minor issue)

### ISSUE THREAD

**Issue by amrutwali** [hasan-py/MERN_Stack_Project_Ecommerce_Hayroo#27]
The Loading Icons spins clockwise, which is the wrong direction according to the arrow direction of the SVG. The rotate direction should be reversed and it will be fine.
![image](https://github.com/hasan-py/MERN_Stack_Project_Ecommerce_Hayroo/assets/54875908/15928134-59f9-45a2-a513-4ee1c81c023e)

**Comment by hasan-py** [comment]
```
<svg
  xmlns="http://www.w3.org/2000/svg"
  fill="none"
  viewBox="0 0 24 24"
  strokeWidth={1.5}
  stroke="currentColor"
  className="w-12 h-12 animate-spin text-gray-600"
>
  <path
    strokeLinecap="round"
    strokeLinejoin="round"
    d="M16.023 9.348h4.992v-.001M2.985 19.644v-4.992m0 0h4.992m-4.993 0l3.181 3.183a8.25 8.25 0 0013.803-3.7M4.031 9.865a8.25 8.25 0 0113.803-3.7l3.181 3.182m0-4.991v4.99"
  />
</svg>
```

Please use this SVG icon for solving this issue. 
Thanks, dear
