### ISSUE TITLE
.env

### ISSUE THREAD

**Issue by Eliseudev96** [hasan-py/MERN_Stack_Project_Ecommerce_Hayroo#30]
I was reviewing your project on GitHub and noticed that the .env file is within the repository scope. I would like to suggest that you consider removing this file from the public scope of the project.

The .env file typically contains sensitive information such as API keys, passwords, and other confidential data. Having it within the project scope can pose a security risk, especially if other people collaborate on the repository or if the project is public.

I suggest you add the .env file to your .gitignore to ensure that it is not included in future commits. This way, sensitive information will not be shared accidentally.

**Comment by hasan-py** [comment]
Thanks for the information; I already knew it. I added this for a reason. Many beginners or newcomers may come and visit the repository without reading the readme. If I hadn't added that, those individuals wouldn't be able to run the project. I've received numerous direct messages about this issue. For that reason, I added the information. No problem regarding the .env file details; they are for text purposes only and pose no security concerns.
