### ISSUE TITLE
Upload issue

### ISSUE THREAD

**Issue by vranacse** [hasan-py/MERN_Stack_Project_Ecommerce_Hayroo#5]
Hi Hasan, this project is awesome but the upload isn't working. as you already quoted `_In uploads folder you need create 3 folder like bellow.
Folder structure will be like: 
public -> uploads -> 1. products 2. customize 3. categories`_

but there is not uploads folder anywhere. Can you share the proper path for the same?

I have tried  creating  server/public/uploads/categories but while doing that getting 

_`POST /api/customize/upload-slide-image 500 1267.869 ms - 277
Error: ENOENT: no such file or directory, open 'public/uploads/categories/1a.jpeg'`_

**Comment by jarno9981** [comment]
@vranacse   how did you fix the image uploading

**Comment by jarno9981** [comment]
@vranacse  now another issues infinity loading
