### ISSUE TITLE
Is there a way to chose options? Like have options for different products

### ISSUE THREAD

**Issue by talmax1124** [hasan-py/MERN_Stack_Project_Ecommerce_Hayroo#6]

**Comment by tranquanghuy0801** [comment]
Could you please explain this more clearly? I thought we already have a set of categories for different products

**Comment by talmax1124** [comment]
Are you referring to Categories in ProductEditScreen. Then yes, we did do that. Buy what I meant is to have like options of sizes like a shirt store would.

**Comment by tranquanghuy0801** [comment]
For that case, you can add a field with different values of options you would like to add in the Admin Panel. This might require some efforts in fixing the frontend and backend.
